aws:
  image_id: "ami-48b69620"
  instance_type: "m1.small"
  region: "us-east-1"
  key_name: "AWS"
  user: "ec2-user"
  tag: "scrapers_manger"
command: "sleep 30"
redis:
  url: "redis://localhost/0"
  queue: "queue"
manager:
  queue_poll_interval_sec: 5
  queue_messages_threshold: 10
  tasks_per_machine: 4
  kill_memory_mb: 1536
